### ISSUE TITLE
the way to "upgrade" 2017031303 to 2017080100

### ISSUE THREAD

**Issue by hjorleifurs** [Panopto/Moodle-2.0-plugin-for-Panopto#116] opened 2017-08-16 16:42 UTC
Just to let you know since it might help someone in the same situation and I'm not sure where else to put it, but we were upgrading the plugin through the moodle page and just used the upgrade button. Everything looked fine to begin with then it just hanged for couple of hours and all we saw on the screen "Site is being upgraded, please try again later". When this happens nothing is written about this in the logs so it was rather difficult to trace what we were doing wrong.

So what finally worked was to go to "Site administration > Plugins > Blocks > Manage blocks", find the panopto block (we had already removed the block directory from the server so it was red with a message missing from disk) and hit uninstall. 
You are greeted with a warning 

"You are about to uninstall the plugin panopto. This will completely delete everything in the database associated with this plugin including its configuration, log records, user files managed by the plugin etc. There is no way back and Moodle itself does not create any recovery backup. Are you SURE you want to continue?
There are 114 instances of this block." (thats the number of courses that were using the block)

Then copy the new block into the blocks directory on the server and update the moodle database as usual and configure the plugin.

So it's rather scary but it was the only thing that worked. So "upgrading" does not work, but **uninstall the old completely and then install the new** is the method that should be used.

So if the upgrade button could do this for this plugin that would be awesome or that there should be a warning in the plugin upgrade that should test if an older version is still in the database and cancel the upgrade with a message telling you to uninstall first or something like that.

**Comment by hitteshahuja** [comment] 2017-08-16 17:24
First of all ,well done on being breve and removing the plugin and re installing it again because that is something we are not in a position to do so as we don't know what folder a  teacher has mapped their course to . You would be tempted to think that the course name and the folder name would match but we must not forget that teachers are allowed to change that by editing the block for their course . It would be logical that because there is nothing to "convert" the plugin installation was successful. But an upgrade should work as an upgrade ,not a fresh install in my opinion. We had to ditch the plugin "upgrade" this year due to the same reason . However tempting a reinstall might be it should be avoided at all cost !

**Comment by jmalmsten-panopto** [comment] 2017-08-16 20:32
Hjörleifur,
Thank you for the report about your experience.

First of all, I would like to point out that the upgrade from prior to 2017061000 version to the latest version triggers certain amount of operations and that causes Moodle's down time. This is explained in detail by this document.

https://support.panopto.com/articles/Documentation/Moodle-Plugin-Upgrade-2017-2017061000

Second, the report includes two unexpected behaviors.

1. Nothing is written in the log:
Upgrade process outputs the log constantly. We realize that this may be cached by operating system before writing down to the physical file. However, as far as we try our Moodle server on Linux, that log is flushed at least once every 5 minutes. There is also a log that happens before any API actions occur, so not seeing any logs indicated a different problem.

2. Upgrade process is stuck for hours with 114 courses.
Our test server completed 1000 courses of upgrade in 50 minutes. Therefore, the report seems too long to complete based on our experience and there may be some unknown blocking issue.

We have not heard either of these behaviors from any other customers yet. If anyone else hits similar situation, please don't hesitate to contact Panopto support team. We are happy to help investigating, and resolving or mitigating the situation.

Finally, let me explain about uninstall - reinstall cycle.
As UI warning says, it cleans up internal data which was created by the plug-in by that time. Our plug-in holds the mapping between Moodle courses and Panopto folders, and uninstall - reinstall cycle clears that information. After this cycle, all the provisioning information was lost and you need to re-provision all courses to recover old state. All instances of the Panopto block are also removed from all courses on an uninstall and need to be re-added in each course. We recommend to take this route only if you do not need to retain old course mapping/block instance.

Thanks,
Joe M

**Closed by jmalmsten-panopto** 2017-08-16 20:32 UTC

**Comment by hjorleifurs** [comment] 2017-08-16 21:36
Hi Joe and thanks for this detailed report. We only did this what I explained earlier on another server which is a copy of our main server so nothing is lost. But we also did this with a support from panopto through a web meeting where I shared my screen (used zoom). But would you then recommend that we first upgrade the plugin to 2017061000 and then to 2017080100? At least I could try that out first on the test server and see what happens but upgrading sounds a lot better than uninstall and reinstall.

all the best
Hjörleifur

**Comment by jmalmsten-panopto** [comment] 2017-08-18 08:22
Hey,

So the login process will only occur once when you are upgrading from an older version of the block to any version at 2017061000 or newer, it only needs to happen once to update old folders to use the new API, and to update any imports to use the new API. If you still need to upgrade I would suggest using the most recent version, as the more recent versions contain improvements to the upgrade process specifically to try and prevent these breaks mid-process. 

There should be logs throughout the process, I would check your PHP error logs on any failures, and include those in any tickets you open with the Panopto support team.

If you come across any problems trying to upgrade with the latest release please contact Panopto support and open a ticket, I can assist better through the support channels.

Regards,
Joe M
